apiVersion: skaffold/v4beta5
#apiVersion: skaffold/v3alpha1
kind: Config
#manifests:
#  rawYaml:
#  - service.yaml
manifests:
  kustomize:
    paths:
      - overlays/dev

metadata:
  name: quotes-llm-helper
build:
# needs 2 artifacts in build phasis since reacjs env variable are changed at build time and build 
# will not occurs between dev and prod in a cloud deploy pipeline 
  artifacts:
  - image: quotes-llm-helper-dev
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
#        REACT_APP_BACK_URL: app.dev.gabrielbechara.com
#        REACT_APP_LLMHELPER_URL: llm.dev.gabrielbechara.com
        REACT_APP_ENV: dev      
  - image: quotes-llm-helper-prod
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
#        REACT_APP_BACK_URL: app.dev.gabrielbechara.com
#        REACT_APP_LLMHELPER_URL: llm.dev.gabrielbechara.com
        REACT_APP_ENV: dev  
deploy:
  cloudrun:
    projectid: qwiklabs-gcp-03-1200b28ed2d1
    region: us-central1
    hooks:
      after:
#       - command: ["sh", "-c", "gcloud run services add-iam-policy-binding quotes-llm-helper-dev --member='user:user@gabrielbechara.altostrat.com' --role='roles/run.invoker' --region=us-central1 --quiet | cat"]
       - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-llm-helper-dev policy.yaml --region=us-central1 --quiet | cat"]

profiles:
- name: dev
  manifests:
    kustomize:
      paths:
        - overlays/dev
  deploy:
    cloudrun:
      projectid: qwiklabs-gcp-03-1200b28ed2d1
      region: us-central1
      hooks:
        after:
        - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-llm-helper-dev policy.yaml --region=us-central1 --quiet | cat"]
  customActions:
  - name: postdeploy-action
    containers:
    - name: postdeploy-apply-policy
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
      command: ["/bin/sh"]
      args: ["-c", "echo $PATH
      &&
      apt-get install -y jq
      &&
      SKAFFOLD_CONFIG_URI=`gcloud deploy releases describe $RELEASE --delivery-pipeline=$PIPELINE --region=$LOCATION --project=$PROJECT --format=json | jq -r \".skaffoldConfigUri\"`
      &&
      gsutil cp $SKAFFOLD_CONFIG_URI .
      &&
      tar xzvf *.tgz
      &&
      cat policy.yaml
      &&
      gcloud run services set-iam-policy quotes-front-dev policy.yaml --region=us-central1 --quiet | cat"]


- name: prod
  manifests:
    kustomize:
      paths:
        - overlays/prod
  deploy:
    cloudrun:
      projectid: qwiklabs-gcp-03-1200b28ed2d1
      region: us-central1
      hooks:
        after:
        - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-prod policy.yaml --region=us-central1 --quiet | cat"]
  customActions:
  - name: postdeploy-action
    containers:
    - name: postdeploy-apply-policy
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
      command: ["/bin/sh"]
      args: ["-c", "echo $PATH
      &&
      apt-get install -y jq
      &&
      SKAFFOLD_CONFIG_URI=`gcloud deploy releases describe $RELEASE --delivery-pipeline=$PIPELINE --region=$LOCATION --project=$PROJECT --format=json | jq -r \".skaffoldConfigUri\"`
      &&
      gsutil cp $SKAFFOLD_CONFIG_URI .
      &&
      tar xzvf *.tgz
      &&
      cat policy.yaml
      &&
      gcloud run services set-iam-policy quotes-front-prod policy.yaml --region=us-central1 --quiet | cat"]

